language: csharp
solution: SE3800InClassProject.sln
install:
  - nuget restore SE3800InClassProject.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SE3800InClassProject.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe SE3800InClassProjectTests/bin/Release/SE3800InClassProjectTests.dll
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "DQbUX4GS4suiwmEEdme7v0lTRVmIqESecHneUCR03mcxEVkU7feTijXygN2yPYHeUODX66qiFFfxBsmsmueovNAHwQP4x5iG9UYtroe1vCJtuD9B1Mf0AaiYJxc5q5siP1L5F8PGnNn0LZEMLOgbkWzkw4yXsk8ye5eXaDG+Yf8="

addons:
  coverity_scan:
    project:
      name: "havemeyerd/SE3800InClassProject"
      description: "Build submitted via Travis CI"
    notification_email: havemeyerd@msoe.edu
    build_command_prepend: "msbuild /t:Clean"
    build_command:   "msbuild /t:Rebuild"
    branch_pattern: coverity_scan